# permissions for end users to view edges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: edge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operatoredge
    app.kubernetes.io/part-of: operatoredge
    app.kubernetes.io/managed-by: kustomize
  name: edge-viewer-role
rules:
- apiGroups:
  - motnitor.edge.operator
  resources:
  - edges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - motnitor.edge.operator
  resources:
  - edges/status
  verbs:
  - get
